### ISSUE TITLE
Fractional bits limited to < 64

### ISSUE THREAD

**Issue by FredKellerman** [francof2a/fxpmath#10]
Nice work I could really use the functionality but fractional precision > 63 does not work for me.  To reproduce try:

from fxpmath import Fxp
fxp = Fxp(1.5, True, 256, 64)

**Comment by francof2a** [comment]
Hello Fred,
I found that limitation because how numpy works with integers. I'm working on try to find a good way to deal with this.
I hope have news soon. Thanks for the feedback!

**Comment by francof2a** [comment]
Hello @FredKellerman ,
It's now supported in version 0.3.7.

Please check if the issue is solved for you.

**Comment by FredKellerman** [comment]
Awesome, works now!  Look me up on LinkedIn so I can show you what I'm doing with this once I finish.  Thanks.
