### ISSUE TITLE
Numpy float128 errors out

### ISSUE THREAD

**Issue by FredKellerman** [francof2a/fxpmath#11]
Again nice work here!  However when I try to use float128 there is a comparison '>' that occurs with an int and the operator is not overloaded for those types.  To reproduce:

from fxpmath import Fxp
import numpy as np
fxp = Fxp(np.float128(1.5), True, 64, 32)

**Comment by francof2a** [comment]
Hello again Fred,
It should be solved in new version 0.3.7.

Please check if it's working now.

**Comment by FredKellerman** [comment]
Love it!  No more errors here or for issue #10.  I'll be pushing this feature up to 256 bits of fixed point precision  You have enabled something really good here!
