### ISSUE TITLE
How to convert an array of strings representing hex? 

### ISSUE THREAD

**Issue by ricardo-jimenez** [francof2a/fxpmath#26]
Does this library support vectorized operations using arrays of strings as inputs?  how?
I am trying to implement something like what you have in the example notebook for [ADC_sampling_quantization](https://github.com/francof2a/fxpmath/blob/master/examples/ADC_sampling_quantization.ipynb) but with the signal being a numpy array of strings. 

For instance using: 
`sig = np.array(['0xff864d8f', '0xff86b76d', '0xff880f87'])`  
in 
`Fxp(sig)` 

I get the following error
<img width="1113" alt="fxpmath_error" src="https://user-images.githubusercontent.com/44005012/109574663-3908c280-7aa5-11eb-8f68-27937367afca.png">

**Comment by francof2a** [comment]
Hi @ricardo-jimenez 
Thank you for reporting this problem.
I was able to reproduce the problem and it is in the best size estimation function.

A workaround is using `tolist` method to pass a list of strings and define the size for the Fxp object:

```python
Fxp(sig.tolist(), signed=False, n_word=32, n_frac=0)
```

I'll be working to solve this!

**Comment by francof2a** [comment]
fixed at v0.4.1
