### ISSUE TITLE
How to get raw representation (as given by hex()) from an Fxp

### ISSUE THREAD

**Issue by aniongithub** [francof2a/fxpmath#36]
Without converting to/from string? I need to convert floats to fixed point and upload them to CUDA memory for computations. All the astype functions convert the actual value and I can't find anything that provides the fixed-point representation.

**Comment by francof2a** [comment]
Hello Ani, first let me convert this issue to a discussion.

I guess you need get the `int` value which represents the raw value of the fixed-point. In that case, you can use `raw` method.

```python
from fxpmath import Fxp

x = Fxp(0.25, dtype='s8.8')
x.raw() # returns 64 as raw value
```

If my assumption is wrong, please write an example with the desired output.
