### ISSUE TITLE
bitwise operation for complex data is confusing 

### ISSUE THREAD

**Issue by RuotingDingKolmostar** [francof2a/fxpmath#54]
bitwise operation of a complex number only applies to real component and yields a non-complex integer,
take `x = Fxp(0b11+0b11*1j, dtype = 'fxp-u2/0-complex')` as an example ,
`x&0b01`  outputs `fxp-u2/0((1+0j))`
the possible expected behaviors should be  : 

- 1 raise an exception for this invalid operation , just like the following 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [51], in <module>
      1 data =0b11+0b11*1j
----> 2 data&0b11

TypeError: unsupported operand type(s) for &: 'complex' and 'int'

```

- 2 apply the  bitwise operation to both real and imag components , this feature should is very useful :) 

thanks

**Comment by ruoting0103** [comment]
sorry very much that I raised the issue with the wrong account ,  I raised another one with correct account alreay https://github.com/francof2a/fxpmath/issues/55 ,
could you help me to remove this issue https://github.com/francof2a/fxpmath/issues/54, thanks a lot
