### ISSUE TITLE
base representation for multidimensional array raised exception

### ISSUE THREAD

**Issue by ruoting0103** [francof2a/fxpmath#56]
`arr_fxp.bin()` for  `arr_fxp = Fxp(np.array([[1,2]]))` raised the following exception:

>     rval = [ utils.binary_repr(int(val.real), n_word=self.n_word, n_frac=n_frac_dot) + '+' + utils.binary_repr(int(val.imag), n_word=self.n_word, n_frac=n_frac_dot) + 'j' for val in self.val]
> TypeError: only size-1 arrays can be converted to Python scalars

**Comment by francof2a** [comment]
Thanks for the issue. It wasn't take into account multidimensional arrays in those representation methods.

I fixed that in the unreleased 0.4.6 version. So, in the next release it will be solved!

**Comment by francof2a** [comment]
Issue solved in v0.4.6
