### ISSUE TITLE
_n_word_max is set to 32 (and not to 64 as one would expect) on a windows 10 64 bit machine

### ISSUE THREAD

**Issue by alb-pol** [francof2a/fxpmath#64]
The reason is this check:
`_test_precision = lambda prec_bits: abs(int(2**np.array(prec_bits-1))) == abs(2**(prec_bits-1))`
specifically **np.array(prec_bits-1)**  . 
Default integer type np.int_ is C long, but C long is int32 in win64: [Stackoverflow](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine)

**Comment by francof2a** [comment]
This is not an issue of **fxpmath** but **numpy** in windows.
This is one of the reasons _fxpmath_ checks the *n_word_max* value to work with `int` type in _numpy_ instead with `object` python type.
