### ISSUE TITLE
Power-operation takes extremely long

### ISSUE THREAD

**Issue by alb-pol** [francof2a/fxpmath#65]
Measuring execution time of power operation as shown in the snippet below, I get the following results on my machine:

a\**2 -> 0.002812599999999943
b\**2 ->  0.514684
c\**2 -> **4.9153115**

compared to d (numpy array):
d\**2 -> 5.50000000032469e-06

```
import numpy as np
from fxpmath import Fxp
import timeit

a = Fxp(2.5, signed=True, n_word=10, n_frac=6, overflow='wrap')
b = Fxp(2.5, signed=True, n_word=13, n_frac=9, overflow='wrap')
c = Fxp(2.5, signed=True, n_word=14, n_frac=10, overflow='wrap')
d = np.array(2.5)

print(timeit.timeit('a**2', globals=globals(), number=1))  
print(timeit.timeit('b**2', globals=globals(), number=1))
print(timeit.timeit('c**2', globals=globals(), number=1))
print(timeit.timeit('d**2', globals=globals(), number=1))
```

**Comment by francof2a** [comment]
When you execute a **powe** function using a `constant`, this constant is converted to a `Fxp` with same format that _base_.
The computation is more expensive using a fixed point number with 10 fractional bit powered with other fixed point number with 10 fractional bits. Additionally to this, converting 2 to `Fxp` a process to calculate the optimal sizes is also time consuming process.

The following alternatives must be faster:

```python
c**Fxp(2) # optimal size is calculated for value 2.
c**Fxp(2, dtype='S8.0') # you can change dtype according your needs or power value.
c**Fxp(2, like=c) # if you want to maintain same size than `c` (this could be slower depending of amount of fractional bits)
```

Performance in my PC:

```python
c**2    # 3.9 s ± 83.7 ms
c**Fxp(2)    # 436 µs ± 40.5 µs
c**Fxp(2, dtype='S8.0')    # 381 µs ± 3.91 µs
c**Fxp(2, like=c)    # 418 µs ± 9.14 µs
```
