### ISSUE TITLE
rshift with expansion

### ISSUE THREAD

**Issue by lpuglia** [francof2a/fxpmath#8]
Hello,

Do you think it would be a good feature to add:
```
if self.shifting == 'expand':
```
clause to ```__rshift__``` operator? Of course this would increase the number of fractional bits.

I think it would make the shift operators more consistent.

**Comment by francof2a** [comment]
Hello,
Yes, you're right! I'll apply this upgrade to the next release.
Thank you

**Comment by francof2a** [comment]
Hello,
It's now supported in version 0.3.7.

Please check if the issue is solved for you.
